name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update submodules (if using a submodule)
      run: git submodule update --init --recursive

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install dotenv package (for environment variables)
      run: npm install dotenv  # Add this line to install dotenv

    - name: Build
      run: npm run build  # Or your build command

    - name: Deploy to Render
      uses: render/deploy-action@master
      with:
        api-key: ${{ secrets.RENDER_API_KEY }}
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        wait-for-success: true